#### Importing the Libraries

In [1]:
import numpy as np
import pandas as pd

#### Creating a Dataset

In [2]:
dataset = pd.DataFrame({'text' : ['anshul posts instagram', 'instagram posts post', 'anshul instagram post', 'post liked instagram', 'liked instagram post'], 'ouput': [1,1,0,0,1]})
dataset

text  ouput
0  anshul posts instagram      1
1    instagram posts post      1
2   anshul instagram post      0
3    post liked instagram      0
4    liked instagram post      1

#### Implementing N-Grams using Count Vectorizer class

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(ngram_range = (1,3))

In [4]:
x = vectorizer.fit_transform(dataset['text'])

#### Printing N-Grams generated for the dataset

In [5]:
print(vectorizer.vocabulary_)

{'anshul': 0, 'posts': 15, 'instagram': 5, 'anshul posts': 3, 'posts instagram': 16, 'anshul posts instagram': 4, 'post': 12, 'instagram posts': 7, 'posts post': 17, 'instagram posts post': 8, 'anshul instagram': 1, 'instagram post': 6, 'anshul instagram post': 2, 'liked': 9, 'post liked': 13, 'liked instagram': 10, 'post liked instagram': 14, 'liked instagram post': 11}


#### Result

In [6]:
print(x[0].toarray())
print(x[1].toarray())

[[1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 1 0]]
[[0 0 0 0 0 1 0 1 1 0 0 0 1 0 0 1 0 1]]


#### Testing N-Grams on new data

In [7]:
vectorizer.transform(["anshul posts instagram instagram liked anshul post"]).toarray()

array([[2, 0, 0, 1, 1, 2, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0]],
      dtype=int64)