#### Importing the Libraries

In [1]:
import numpy as np
import pandas as pd

#### Creating a Dataset

In [2]:
dataset = pd.DataFrame({'text' : ['anshul posts instagram', 'instagram posts post', 'anshul instagram post', 'post liked instagram', 'liked instagram post'], 'ouput': [1,1,0,0,1]})
dataset

text  ouput
0  anshul posts instagram      1
1    instagram posts post      1
2   anshul instagram post      0
3    post liked instagram      0
4    liked instagram post      1

#### Implementing Tf-Idf using Count Vectorizer class

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
x = vectorizer.fit_transform(dataset['text']).toarray()

#### Checking values calculated by Tf-Idf class

In [4]:
print(vectorizer.idf_)
print(vectorizer.get_feature_names_out())

[1.69314718 1.         1.69314718 1.18232156 1.69314718]
['anshul' 'instagram' 'liked' 'post' 'posts']


#### Result

In [5]:
print(x[0])
print(x[1])

[0.65249088 0.38537163 0.         0.         0.65249088]
[0.         0.43582888 0.         0.51528988 0.73792244]
