#### Importing the Libraries

In [1]:
import numpy as np
import pandas as pd

#### Creating a Dataset

In [4]:
dataset = pd.DataFrame({'text' : ['anshul posts instagram', 'instagram posts post', 'anshul instagram post', 'post liked instagram', 'liked instagram post'], 'ouput': [1,1,0,0,1]})
dataset

text  ouput
0  anshul posts instagram      1
1    instagram posts post      1
2   anshul instagram post      0
3    post liked instagram      0
4    liked instagram post      1

#### Implementing Bag of Words using Count Vectorizer class

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

In [7]:
x = vectorizer.fit_transform(dataset['text'])

#### Printing unique words in the dataset

In [9]:
print(vectorizer.vocabulary_)

{'anshul': 0, 'posts': 4, 'instagram': 1, 'post': 3, 'liked': 2}


In [10]:
print(x[0].toarray())
print(x[1].toarray())

[[1 1 0 0 1]]
[[0 1 0 1 1]]


In [11]:
vectorizer.transform(["anshul posts instagram instagram liked anshul post"]).toarray()

array([[2, 2, 1, 1, 1]], dtype=int64)